kind: DHelmDT

# positions are done by pre-trained model
global_pos_embds: True
relative_pos_embds: False
use_time_embds: False
stochastic_policy: False

# rettrieve based on s,a,r,rtg
reward_condition: True
rtg_condition: True

# frozenhopfield
on_rtgs: True

# tokenization
tokenize_a: False
tokenize_r: True
tokenize_rtg: True
tokenize_s: True
r_tok_kwargs: 
  min_val: 0
  max_val: 1
  vocab_size: 2
rtg_tok_kwargs: 
  min_val: 0
  max_val: 800
  vocab_size: 800
s_tok_kwargs: 
  min_val: 0
  max_val: 39
  vocab_size: 40
  one_hot: True
