kind: "DDT"
use_critic: False
learning_starts: 0
batch_size: 128
gradient_steps: 1
stochastic_policy: False
persist_context: False
ent_coef: 0.0
offline_steps: ${run_params.total_timesteps}
buffer_max_len_type: "transition"
buffer_size: 120000000 # 12e7
buffer_weight_by: len 
target_return_type: fixed
warmup_steps: 4000
use_amp: True 
compile: True

replay_buffer_kwargs:
  num_workers: 16
  pin_memory: False
  init_top_p: 1

defaults:
  - huggingface: dt_medium_64
  - data_paths: dark_room_10x10_sfixed_grand_train
  - model_kwargs: dark_room
  - lr_sched_kwargs: cosine

huggingface:
  # max_ep_len: 201
  activation_function: gelu
  max_length: 50
  use_fast_attn: True
  n_positions: 1600
eval_context_len: ${agent_params.huggingface.max_length}

model_kwargs: 
  global_pos_embds: True