envid: MiniHack-Room-Dark-Dense-40x20-v0
target_return: 1
num_envs: 1
norm_obs: False
record: False
record_freq: 1000000
record_length: 2000
reward_scale: 1

# randomly selected positions
# 80 for training, 20 for testing
env_kwargs: 
  random: False
  observation_keys: 
    - tty_cursor

train_start_pos: 
  - [0,0]
train_goal_pos: 
  - [29, 6]
  - [38, 6]
  - [36, 2]
  - [29, 0]
  - [27, 2]
  - [32, 7]
  - [10, 8]
  - [36, 11]
  - [37, 18]
  - [9, 8]
  - [8, 16]
  - [10, 10]
  - [13, 8]
  - [6, 2]
  - [4, 11]
  - [17, 17]
  - [12, 16]
  - [34, 1]
  - [20, 16]
  - [32, 9]
  - [19, 4]
  - [11, 10]
  - [16, 14]
  - [19, 6]
  - [27, 15]
  - [17, 2]
  - [28, 4]
  - [18, 14]
  - [26, 7]
  - [30, 15]
  - [17, 8]
  - [35, 10]
  - [15, 14]
  - [24, 0]
  - [6, 8]
  - [19, 12]
  - [11, 17]
  - [19, 18]
  - [26, 16]
  - [22, 13]
  - [0, 11]
  - [0, 17]
  - [39, 2]
  - [39, 8]
  - [19, 14]
  - [21, 8]
  - [25, 15]
  - [4, 2]
  - [4, 14]
  - [1, 4]
  - [34, 12]
  - [11, 8]
  - [37, 5]
  - [18, 9]
  - [25, 4]
  - [22, 16]
  - [20, 6]
  - [18, 0]
  - [35, 8]
  - [9, 10]
  - [12, 1]
  - [34, 16]
  - [38, 17]
  - [20, 18]
  - [39, 3]
  - [35, 5]
  - [3, 7]
  - [16, 11]
  - [31, 0]
  - [14, 17]
  - [23, 4]
  - [12, 10]
  - [2, 7]
  - [29, 13]
  - [25, 12]
  - [9, 16]
  - [13, 9]
  - [20, 4]
  - [2, 17]
  - [26, 10]

# train tasks for sfixed, grand
eval_start_pos: [0, 0]
eval_goal_pos:
  - [14, 13]
  - [31, 2]
  - [5, 19]
  - [18, 5]
  - [29, 9]
  - [5, 11]
  - [28, 8]
  - [22, 10]
  - [1, 15]
  - [27, 11]
  - [15, 17]
  - [5, 5]
  - [4, 8]
  - [38, 5]
  - [21, 6]
  - [24, 15]
  - [7, 19]
  - [13, 16]
  - [13, 1]
  - [12, 9]
