envid: MiniHack-Room-Dark-Dense-20x20-v0
target_return: 1
num_envs: 1
norm_obs: False
record: False
record_freq: 1000000
record_length: 2000
reward_scale: 1

# randomly selected positions
# 80 for training, 20 for testing
env_kwargs: 
  random: False
  observation_keys: 
    - tty_cursor

train_start_pos: 
  - [0,0]

train_goal_pos: 
  - [2, 15]
  - [13, 11]
  - [19, 10]
  - [5, 5]
  - [11, 3]
  - [17, 18]
  - [1, 0]
  - [15, 9]
  - [19, 15]
  - [6, 19]
  - [6, 18]
  - [9, 5]
  - [4, 14]
  - [4, 2]
  - [18, 1]
  - [19, 2]
  - [7, 3]
  - [17, 15]
  - [16, 8]
  - [17, 9]
  - [15, 1]
  - [3, 4]
  - [1, 7]
  - [11, 8]
  - [19, 16]
  - [6, 16]
  - [3, 7]
  - [12, 3]
  - [8, 19]
  - [11, 14]
  - [16, 18]
  - [14, 4]
  - [0, 12]
  - [11, 13]
  - [17, 1]
  - [3, 2]
  - [11, 10]
  - [2, 19]
  - [11, 9]
  - [5, 3]
  - [16, 2]
  - [19, 9]
  - [0, 15]
  - [10, 7]
  - [2, 4]
  - [12, 17]
  - [17, 5]
  - [19, 1]
  - [8, 16]
  - [13, 3]
  - [0, 3]
  - [10, 5]
  - [11, 1]
  - [16, 1]
  - [0, 17]
  - [12, 7]
  - [6, 1]
  - [8, 5]
  - [13, 1]
  - [18, 18]
  - [16, 5]
  - [1, 9]
  - [19, 8]
  - [1, 10]
  - [0, 0]
  - [16, 7]
  - [9, 10]
  - [13, 6]
  - [15, 12]
  - [1, 18]
  - [18, 4]
  - [3, 9]
  - [15, 6]
  - [1, 16]
  - [18, 8]
  - [6, 6]
  - [7, 0]
  - [18, 0]
  - [14, 9]
  - [9, 3]

# train tasks for sfixed, grand
eval_start_pos: [0, 0]
eval_goal_pos:
  - [16, 12]
  - [9, 15]
  - [1, 6]
  - [5, 17]
  - [7, 17]
  - [8, 17]
  - [10, 14]
  - [9, 19]
  - [10, 10]
  - [16, 17]
  - [8, 6]
  - [9, 13]
  - [15, 8]
  - [15, 18]
  - [15, 15]
  - [3, 18]
  - [17, 17]
  - [10, 8]
  - [5, 2]
  - [0, 18]
