envid: MiniHack-Room-Dark-Dense-10x10-v0
target_return: [90,5]
num_envs: 1
norm_obs: False
record: False
record_freq: 1000000
record_length: 2000
reward_scale: 1

# randomly selected positions
# 80 for training, 20 for testing
env_kwargs: 
  random: False
  observation_keys: 
    - tty_cursor

train_start_pos: 
  - [0,0]

train_goal_pos: 
  - [2, 0]
  - [0, 2]
  - [1, 5]
  - [2, 2]
  - [5, 7]
  - [9, 1]
  - [6, 9]
  - [5, 5]
  - [1, 1]
  - [7, 9]
  - [0, 9]
  - [3, 8]
  - [8, 5]
  - [0, 0]
  - [8, 9]
  - [1, 3]
  - [0, 5]
  - [0, 1]
  - [9, 5]
  - [8, 3]
  - [4, 4]
  - [1, 2]
  - [7, 8]
  - [9, 4]
  - [3, 7]
  - [9, 2]
  - [9, 7]
  - [5, 6]
  - [6, 3]
  - [4, 6]
  - [0, 8]
  - [3, 3]
  - [4, 5]
  - [1, 9]
  - [1, 4]
  - [9, 3]
  - [7, 3]
  - [3, 9]
  - [2, 4]
  - [0, 6]
  - [6, 2]
  - [2, 3]
  - [1, 8]
  - [4, 2]
  - [8, 0]
  - [8, 6]
  - [3, 1]
  - [6, 7]
  - [2, 7]
  - [1, 0]
  - [4, 0]
  - [7, 0]
  - [9, 6]
  - [8, 8]
  - [2, 6]
  - [5, 4]
  - [7, 1]
  - [2, 9]
  - [2, 5]
  - [4, 3]
  - [4, 1]
  - [7, 2]
  - [0, 3]
  - [8, 1]
  - [5, 3]
  - [7, 7]
  - [6, 1]
  - [0, 7]
  - [2, 8]
  - [9, 9]
  - [5, 2]
  - [4, 8]
  - [8, 2]
  - [6, 0]
  - [7, 4]
  - [3, 2]
  - [4, 7]
  - [7, 6]
  - [3, 6]
  - [0, 4]

# train tasks for sfixed, grand
eval_start_pos: [0, 0]
eval_goal_pos:    
  - [9, 0]
  - [8, 4]
  - [3, 4]
  - [6, 5]
  - [7, 5]
  - [5, 0]
  - [3, 5]
  - [9, 8]
  - [8, 7]
  - [3, 0]
  - [6, 6]
  - [5, 9]
  - [1, 7]
  - [5, 1]
  - [1, 6]
  - [5, 8]
  - [2, 1]
  - [4, 9]
  - [6, 4]
  - [6, 8]
