envid: MiniHack-KeyDoor-Dark-Dense-10x10-v0
target_return: [90,5]
num_envs: 1
norm_obs: False
record: False
record_freq: 1000000
record_length: 2000
reward_scale: 1

# randomly selected positions
# 80 for training, 20 for testing
env_kwargs: 
  random: False
  observation_keys: 
    - tty_cursor

train_start_pos: 
  - [0,0]
train_goal_pos: 
  - [2,0]
  - [0,2]
  - [1,5]
  - [2,2]
  - [5,7]
  - [9,1]
  - [6,9]
  - [5,5]
  - [1,1]
  - [7,9]
  - [0,9]
  - [3,8]
  - [8,5]
  - [0,0]
  - [8,9]
  - [1,3]
  - [0,5]
  - [0,1]
  - [9,5]
  - [8,3]
  - [4,4]
  - [1,2]
  - [7,8]
  - [9,4]
  - [3,7]
  - [9,2]
  - [9,7]
  - [5,6]
  - [6,3]
  - [4,6]
  - [0,8]
  - [3,3]
  - [4,5]
  - [1,9]
  - [1,4]
  - [9,3]
  - [7,3]
  - [3,9]
  - [2,4]
  - [0,6]
  - [6,2]
  - [2,3]
  - [1,8]
  - [4,2]
  - [8,0]
  - [8,6]
  - [3,1]
  - [6,7]
  - [2,7]
  - [1,0]
  - [4,0]
  - [7,0]
  - [9,6]
  - [8,8]
  - [2,6]
  - [5,4]
  - [7,1]
  - [2,9]
  - [2,5]
  - [4,3]
  - [4,1]
  - [7,2]
  - [0,3]
  - [8,1]
  - [5,3]
  - [7,7]
  - [6,1]
  - [0,7]
  - [2,8]
  - [9,9]
  - [5,2]
  - [4,8]
  - [8,2]
  - [6,0]
  - [7,4]
  - [3,2]
  - [4,7]
  - [7,6]
  - [3,6]
  - [0,4]
train_key_pos:
  - [8,3]
  - [5,3]
  - [7,0]
  - [4,5]
  - [4,4]
  - [3,9]
  - [2,2]
  - [8,0]
  - [1,0]
  - [0,0]
  - [1,8]
  - [3,0]
  - [7,3]
  - [3,3]
  - [9,0]
  - [0,4]
  - [7,6]
  - [7,7]
  - [1,2]
  - [3,1]
  - [5,5]
  - [8,8]
  - [2,6]
  - [4,2]
  - [6,9]
  - [1,5]
  - [4,0]
  - [9,6]
  - [0,9]
  - [7,2]
  - [1,1]
  - [4,7]
  - [8,5]
  - [2,8]
  - [9,3]
  - [0,5]
  - [6,6]
  - [6,5]
  - [3,5]
  - [1,6]
  - [4,9]
  - [3,4]
  - [0,7]
  - [9,5]
  - [2,7]
  - [1,9]
  - [8,1]
  - [2,5]
  - [6,2]
  - [1,3]
  - [2,4]
  - [0,3]
  - [1,7]
  - [3,8]
  - [0,8]
  - [7,8]
  - [0,6]
  - [6,4]
  - [3,6]
  - [8,9]
  - [5,6]
  - [9,9]
  - [5,4]
  - [4,3]
  - [5,0]
  - [6,7]
  - [4,6]
  - [6,8]
  - [6,1]
  - [9,7]
  - [7,9]
  - [4,1]
  - [5,8]
  - [4,8]
  - [9,8]
  - [5,7]
  - [7,5]
  - [3,2]
  - [9,4]
  - [5,9]

# train tasks for sfixed, grand
eval_start_pos: [0, 0]
eval_goal_pos:    
  - [9,0]
  - [8,4]
  - [3,4]
  - [6,5]
  - [7,5]
  - [5,0]
  - [3,5]
  - [9,8]
  - [8,7]
  - [3,0]
  - [6,6]
  - [5,9]
  - [1,7]
  - [5,1]
  - [1,6]
  - [5,8]
  - [2,1]
  - [4,9]
  - [6,4]
  - [6,8] 
eval_key_pos: 
  - [6,3]
  - [3,1]
  - [3,7]
  - [2,9]
  - [0,1]
  - [5,2]
  - [2,1]
  - [0,2]
  - [2,3]
  - [8,7]
  - [9,1]
  - [7,4]
  - [8,6]
  - [8,2]
  - [2,0]
  - [6,0]
  - [7,1]
  - [1,4]
  - [9,2]
  - [5,1]
