envid: dmcontrol11_icl
reward_scale: 100
target_return: 1000
num_envs: 1
norm_obs: False
record: False
record_freq: 250000
record_length: 1000
eval_env_names: "dmcontrol5_icl"
dmc_env_kwargs: 
  flatten_obs: False
