- finger_turn_easy.npz
- fish_upright.npz
- hopper_stand.npz
- point_mass_easy.npz
- walker_stand.npz
- walker_run.npz
- ball_in_cup_catch.npz
- cartpole_swingup.npz
- cheetah_run.npz
- finger_spin.npz
- reacher_easy.npz