max_length: 20
# n_embd is not actually used! hidden_size is also used for the embedding dim in the DT implementation...
n_embd: 512
n_layer: 4
n_head: 4
max_ep_len: 1000
hidden_size: 512
output_attentions: True