  base: ${DATA_DIR}/minihack/dark_room/10x10
  names: 
  - "[0,0]_[2,0].pkl"
  - "[0,0]_[0,2].pkl"
  - "[0,0]_[1,5].pkl"
  - "[0,0]_[2,2].pkl"
  - "[0,0]_[5,7].pkl"
  - "[0,0]_[9,1].pkl"
  - "[0,0]_[6,9].pkl"
  - "[0,0]_[5,5].pkl"
  - "[0,0]_[1,1].pkl"
  - "[0,0]_[7,9].pkl"
  - "[0,0]_[0,9].pkl"
  - "[0,0]_[3,8].pkl"
  - "[0,0]_[8,5].pkl"
  - "[0,0]_[0,0].pkl"
  - "[0,0]_[8,9].pkl"
  - "[0,0]_[1,3].pkl"
  - "[0,0]_[0,5].pkl"
  - "[0,0]_[0,1].pkl"
  - "[0,0]_[9,5].pkl"
  - "[0,0]_[8,3].pkl"
  - "[0,0]_[4,4].pkl"
  - "[0,0]_[1,2].pkl"
  - "[0,0]_[7,8].pkl"
  - "[0,0]_[9,4].pkl"
  - "[0,0]_[3,7].pkl"
  - "[0,0]_[9,2].pkl"
  - "[0,0]_[9,7].pkl"
  - "[0,0]_[5,6].pkl"
  - "[0,0]_[6,3].pkl"
  - "[0,0]_[4,6].pkl"
  - "[0,0]_[0,8].pkl"
  - "[0,0]_[3,3].pkl"
  - "[0,0]_[4,5].pkl"
  - "[0,0]_[1,9].pkl"
  - "[0,0]_[1,4].pkl"
  - "[0,0]_[9,3].pkl"
  - "[0,0]_[7,3].pkl"
  - "[0,0]_[3,9].pkl"
  - "[0,0]_[2,4].pkl"
  - "[0,0]_[0,6].pkl"
  - "[0,0]_[6,2].pkl"
  - "[0,0]_[2,3].pkl"
  - "[0,0]_[1,8].pkl"
  - "[0,0]_[4,2].pkl"
  - "[0,0]_[8,0].pkl"
  - "[0,0]_[8,6].pkl"
  - "[0,0]_[3,1].pkl"
  - "[0,0]_[6,7].pkl"
  - "[0,0]_[2,7].pkl"
  - "[0,0]_[1,0].pkl"
  - "[0,0]_[4,0].pkl"
  - "[0,0]_[7,0].pkl"
  - "[0,0]_[9,6].pkl"
  - "[0,0]_[8,8].pkl"
  - "[0,0]_[2,6].pkl"
  - "[0,0]_[5,4].pkl"
  - "[0,0]_[7,1].pkl"
  - "[0,0]_[2,9].pkl"
  - "[0,0]_[2,5].pkl"
  - "[0,0]_[4,3].pkl"
  - "[0,0]_[4,1].pkl"
  - "[0,0]_[7,2].pkl"
  - "[0,0]_[0,3].pkl"
  - "[0,0]_[8,1].pkl"
  - "[0,0]_[5,3].pkl"
  - "[0,0]_[7,7].pkl"
  - "[0,0]_[6,1].pkl"
  - "[0,0]_[0,7].pkl"
  - "[0,0]_[2,8].pkl"
  - "[0,0]_[9,9].pkl"
  - "[0,0]_[5,2].pkl"
  - "[0,0]_[4,8].pkl"
  - "[0,0]_[8,2].pkl"
  - "[0,0]_[6,0].pkl"
  - "[0,0]_[7,4].pkl"
  - "[0,0]_[3,2].pkl"
  - "[0,0]_[4,7].pkl"
  - "[0,0]_[7,6].pkl"
  - "[0,0]_[3,6].pkl"
  - "[0,0]_[0,4].pkl"