  base: ${DATA_DIR}/minihack/dark_room/20x20
  names: 
  - "[0,0]_[2,15].pkl"
  - "[0,0]_[13,11].pkl"
  - "[0,0]_[19,10].pkl"
  - "[0,0]_[5,5].pkl"
  - "[0,0]_[11,3].pkl"
  - "[0,0]_[17,18].pkl"
  - "[0,0]_[1,0].pkl"
  - "[0,0]_[15,9].pkl"
  - "[0,0]_[19,15].pkl"
  - "[0,0]_[6,19].pkl"
  - "[0,0]_[6,18].pkl"
  - "[0,0]_[9,5].pkl"
  - "[0,0]_[4,14].pkl"
  - "[0,0]_[4,2].pkl"
  - "[0,0]_[18,1].pkl"
  - "[0,0]_[19,2].pkl"
  - "[0,0]_[7,3].pkl"
  - "[0,0]_[17,15].pkl"
  - "[0,0]_[16,8].pkl"
  - "[0,0]_[17,9].pkl"
  - "[0,0]_[15,1].pkl"
  - "[0,0]_[3,4].pkl"
  - "[0,0]_[1,7].pkl"
  - "[0,0]_[11,8].pkl"
  - "[0,0]_[19,16].pkl"
  - "[0,0]_[6,16].pkl"
  - "[0,0]_[3,7].pkl"
  - "[0,0]_[12,3].pkl"
  - "[0,0]_[8,19].pkl"
  - "[0,0]_[11,14].pkl"
  - "[0,0]_[16,18].pkl"
  - "[0,0]_[14,4].pkl"
  - "[0,0]_[0,12].pkl"
  - "[0,0]_[11,13].pkl"
  - "[0,0]_[17,1].pkl"
  - "[0,0]_[3,2].pkl"
  - "[0,0]_[11,10].pkl"
  - "[0,0]_[2,19].pkl"
  - "[0,0]_[11,9].pkl"
  - "[0,0]_[5,3].pkl"
  - "[0,0]_[16,2].pkl"
  - "[0,0]_[19,9].pkl"
  - "[0,0]_[0,15].pkl"
  - "[0,0]_[10,7].pkl"
  - "[0,0]_[2,4].pkl"
  - "[0,0]_[12,17].pkl"
  - "[0,0]_[17,5].pkl"
  - "[0,0]_[19,1].pkl"
  - "[0,0]_[8,16].pkl"
  - "[0,0]_[13,3].pkl"
  - "[0,0]_[0,3].pkl"
  - "[0,0]_[10,5].pkl"
  - "[0,0]_[11,1].pkl"
  - "[0,0]_[16,1].pkl"
  - "[0,0]_[0,17].pkl"
  - "[0,0]_[12,7].pkl"
  - "[0,0]_[6,1].pkl"
  - "[0,0]_[8,5].pkl"
  - "[0,0]_[13,1].pkl"
  - "[0,0]_[18,18].pkl"
  - "[0,0]_[16,5].pkl"
  - "[0,0]_[1,9].pkl"
  - "[0,0]_[19,8].pkl"
  - "[0,0]_[1,10].pkl"
  - "[0,0]_[0,0].pkl"
  - "[0,0]_[16,7].pkl"
  - "[0,0]_[9,10].pkl"
  - "[0,0]_[13,6].pkl"
  - "[0,0]_[15,12].pkl"
  - "[0,0]_[1,18].pkl"
  - "[0,0]_[18,4].pkl"
  - "[0,0]_[3,9].pkl"
  - "[0,0]_[15,6].pkl"
  - "[0,0]_[1,16].pkl"
  - "[0,0]_[18,8].pkl"
  - "[0,0]_[6,6].pkl"
  - "[0,0]_[7,0].pkl"
  - "[0,0]_[18,0].pkl"
  - "[0,0]_[14,9].pkl"
  - "[0,0]_[9,3].pkl"
