  base: ${DATA_DIR}/minihack/dark_room/40x20
  names: 
  - "[0,0]_[29,6].pkl"
  - "[0,0]_[38,6].pkl"
  - "[0,0]_[36,2].pkl"
  - "[0,0]_[29,0].pkl"
  - "[0,0]_[27,2].pkl"
  - "[0,0]_[32,7].pkl"
  - "[0,0]_[10,8].pkl"
  - "[0,0]_[36,11].pkl"
  - "[0,0]_[37,18].pkl"
  - "[0,0]_[9,8].pkl"
  - "[0,0]_[8,16].pkl"
  - "[0,0]_[10,10].pkl"
  - "[0,0]_[13,8].pkl"
  - "[0,0]_[6,2].pkl"
  - "[0,0]_[4,11].pkl"
  - "[0,0]_[17,17].pkl"
  - "[0,0]_[12,16].pkl"
  - "[0,0]_[34,1].pkl"
  - "[0,0]_[20,16].pkl"
  - "[0,0]_[32,9].pkl"
  - "[0,0]_[19,4].pkl"
  - "[0,0]_[11,10].pkl"
  - "[0,0]_[16,14].pkl"
  - "[0,0]_[19,6].pkl"
  - "[0,0]_[27,15].pkl"
  - "[0,0]_[17,2].pkl"
  - "[0,0]_[28,4].pkl"
  - "[0,0]_[18,14].pkl"
  - "[0,0]_[26,7].pkl"
  - "[0,0]_[30,15].pkl"
  - "[0,0]_[17,8].pkl"
  - "[0,0]_[35,10].pkl"
  - "[0,0]_[15,14].pkl"
  - "[0,0]_[24,0].pkl"
  - "[0,0]_[6,8].pkl"
  - "[0,0]_[19,12].pkl"
  - "[0,0]_[11,17].pkl"
  - "[0,0]_[19,18].pkl"
  - "[0,0]_[26,16].pkl"
  - "[0,0]_[22,13].pkl"
  - "[0,0]_[0,11].pkl"
  - "[0,0]_[0,17].pkl"
  - "[0,0]_[39,2].pkl"
  - "[0,0]_[39,8].pkl"
  - "[0,0]_[19,14].pkl"
  - "[0,0]_[21,8].pkl"
  - "[0,0]_[25,15].pkl"
  - "[0,0]_[4,2].pkl"
  - "[0,0]_[4,14].pkl"
  - "[0,0]_[1,4].pkl"
  - "[0,0]_[34,12].pkl"
  - "[0,0]_[11,8].pkl"
  - "[0,0]_[37,5].pkl"
  - "[0,0]_[18,9].pkl"
  - "[0,0]_[25,4].pkl"
  - "[0,0]_[22,16].pkl"
  - "[0,0]_[20,6].pkl"
  - "[0,0]_[18,0].pkl"
  - "[0,0]_[35,8].pkl"
  - "[0,0]_[9,10].pkl"
  - "[0,0]_[12,1].pkl"
  - "[0,0]_[34,16].pkl"
  - "[0,0]_[38,17].pkl"
  - "[0,0]_[20,18].pkl"
  - "[0,0]_[39,3].pkl"
  - "[0,0]_[35,5].pkl"
  - "[0,0]_[3,7].pkl"
  - "[0,0]_[16,11].pkl"
  - "[0,0]_[31,0].pkl"
  - "[0,0]_[14,17].pkl"
  - "[0,0]_[23,4].pkl"
  - "[0,0]_[12,10].pkl"
  - "[0,0]_[2,7].pkl"
  - "[0,0]_[29,13].pkl"
  - "[0,0]_[25,12].pkl"
  - "[0,0]_[9,16].pkl"
  - "[0,0]_[13,9].pkl"
  - "[0,0]_[20,4].pkl"
  - "[0,0]_[2,17].pkl"
  - "[0,0]_[26,10].pkl"
