base: ${DATA_DIR}/mazerunner/15x15
names: 
- "0.pkl"
- "1.pkl"
- "3.pkl"
- "4.pkl"
- "6.pkl"
- "7.pkl"
- "8.pkl"
- "9.pkl"
- "11.pkl"
- "12.pkl"
- "14.pkl"
- "16.pkl"
- "17.pkl"
- "18.pkl"
- "19.pkl"
- "20.pkl"
- "22.pkl"
- "23.pkl"
- "25.pkl"
- "26.pkl"
- "28.pkl"
- "30.pkl"
- "32.pkl"
- "33.pkl"
- "34.pkl"
- "35.pkl"
- "37.pkl"
- "38.pkl"
- "40.pkl"
- "41.pkl"
- "42.pkl"
- "43.pkl"
- "44.pkl"
- "45.pkl"
- "46.pkl"
- "47.pkl"
- "48.pkl"
- "49.pkl"
- "50.pkl"
- "51.pkl"
- "54.pkl"
- "55.pkl"
- "56.pkl"
- "58.pkl"
- "60.pkl"
- "61.pkl"
- "62.pkl"
- "63.pkl"
- "64.pkl"
- "65.pkl"
- "66.pkl"
- "67.pkl"
- "68.pkl"
- "69.pkl"
- "70.pkl"
- "71.pkl"
- "72.pkl"
- "73.pkl"
- "74.pkl"
- "75.pkl"
- "76.pkl"
- "77.pkl"
- "79.pkl"
- "80.pkl"
- "81.pkl"
- "82.pkl"
- "83.pkl"
- "84.pkl"
- "85.pkl"
- "86.pkl"
- "87.pkl"
- "88.pkl"
- "89.pkl"
- "90.pkl"
- "91.pkl"
- "92.pkl"
- "93.pkl"
- "95.pkl"
- "96.pkl"
- "97.pkl"
- "98.pkl"
- "99.pkl"
- "100.pkl"
- "101.pkl"
- "102.pkl"
- "103.pkl"
- "104.pkl"
- "106.pkl"
- "108.pkl"
- "109.pkl"
- "110.pkl"
- "111.pkl"
- "112.pkl"
- "113.pkl"
- "116.pkl"
- "117.pkl"
- "118.pkl"
- "119.pkl"
- "120.pkl"
- "121.pkl"