base: ${SSD_DATA_DIR}/procgen_2M
names: 
  - "bigfish"
  - "bossfight"
  - "caveflyer"
  - "chaser"
  - "coinrun"
  - "dodgeball" 
  - "fruitbot"
  - "heist"
  - "leaper"
  - "maze"
  - "miner"
  - "starpilot"